app/tasks/forms.py
import datetime

from flask import g
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, IntegerField, SelectField, SubmitField
from wtforms.validators import DataRequired, ValidationError

from app.models import Worker


class TaskForm(FlaskForm):
    description = StringField("Task description", validators=[DataRequired()])
    deadline = DateField("Deadline, format: Y-M-D")
    priority = SelectField("Priority", choices=[i for i in range(1, 6)])
    executor_name = StringField("Executor name", validators=[DataRequired()])
    submit = SubmitField("Submit")

    def validate_deadline(self, deadline):
        if deadline.data:
            if deadline.data < datetime.date.today() + datetime.timedelta(days=1):
                raise ValidationError("Deadline must be tomorrow at the earliest.")

    def validate_executor_name(self, executor_name):
        if not Worker.get_by_username(g.current_invest.id, executor_name.data).id:
            raise ValidationError(
                "We can not find worker with this name. Check typing and try again."
            )


class ProgressForm(FlaskForm):
    progress = IntegerField("Progress")
    submit = SubmitField("Submit")

    def validate_progress(self, progress):
        if not isinstance(progress.data, int):
            progress.data = 0
        if progress.data < 0:
            raise ValidationError("Progress value can not be negative!")
        if progress.data > 100:
            raise ValidationError("Progress value can not be greater than 100!")

app/tasks/__init__.py
from flask import Blueprint

bp = Blueprint("tasks", __name__)

from app.tasks import routes

app/tasks/routes.py
from flask import render_template, redirect, url_for, flash, g, request
from flask_login import login_required, current_user

from app import db, r
from app.main.forms import WarrantyForm
from app.models import Task, Worker
from app.redis_client import create_notification, add_notification
from app.tasks import bp
from app.tasks.forms import TaskForm, ProgressForm


@bp.route("/")
@login_required
def tasks():
    new_tasks = g.current_worker.get_new_tasks()
    if g.current_worker.id:
        g.current_worker.update_last_activity("last_time_tasks_displayed")
    tasks_in_progress = Task.get_in_progress(invest_id=g.current_invest.id)
    realized_tasks = Task.get_realized(invest_id=g.current_invest.id)
    admin = Worker.is_admin(user_id=current_user.id, investment_id=g.current_invest.id)
    next_page = url_for("tasks.tasks")
    return render_template(
        "tasks/tasks.html",
        title="Tasks",
        new_tasks=new_tasks,
        tasks_in_progress=tasks_in_progress,
        realized_tasks=realized_tasks,
        admin=admin,
        next_page=next_page,
    )


@bp.route("/my")
@login_required
def my_tasks():
    # TODO wrap queries in functions

    tasks_in_progress = (
        Worker.get_by_username(
            invest_id=g.current_invest.id, username=current_user.username
        )
        .tasks_to_execution.filter(Task.progress != 100)
        .order_by(Task.deadline)
        .order_by(Task.priority.desc())
        .all()
    )
    realized_tasks = (
        Worker.get_by_username(
            invest_id=g.current_invest.id, username=current_user.username
        )
        .tasks_to_execution.filter(Task.progress == 100)
        .order_by(Task.deadline)
        .order_by(Task.priority.desc())
        .all()
    )
    admin = Worker.is_admin(user_id=current_user.id, investment_id=g.current_invest.id)
    next_page = url_for("tasks.my_tasks")
    return render_template(
        "tasks/tasks.html",
        title="My Tasks",
        tasks_in_progress=tasks_in_progress,
        realized_tasks=realized_tasks,
        admin=admin,
        next_page=next_page,
    )


@bp.route("/deputed")
@login_required
def deputed_tasks():
    # TODO wrap queries in functions

    tasks_in_progress = (
        Worker.get_by_username(
            invest_id=g.current_invest.id, username=current_user.username
        )
        .deputed_tasks.filter(Task.progress != 100)
        .order_by(Task.deadline)
        .order_by(Task.priority.desc())
        .all()
    )
    realized_tasks = (
        Worker.get_by_username(
            invest_id=g.current_invest.id, username=current_user.username
        )
        .deputed_tasks.filter(Task.progress == 100)
        .order_by(Task.deadline)
        .order_by(Task.priority.desc())
        .all()
    )
    admin = Worker.is_admin(user_id=current_user.id, investment_id=g.current_invest.id)
    next_page = url_for("tasks.deputed_tasks")
    return render_template(
        "tasks/tasks.html",
        title="Deputed Tasks",
        tasks_in_progress=tasks_in_progress,
        realized_tasks=realized_tasks,
        admin=admin,
        next_page=next_page,
    )


@bp.route("/add", methods=["GET", "POST"])
@login_required
def add_task():
    orderer = Worker.get_by_username(g.current_invest.id, current_user.username)
    if not orderer.id:
        flash("Choose investment first.")
        return redirect(url_for("tasks.tasks"))
    form = TaskForm()
    if form.validate_on_submit():
        executor = Worker.get_by_username(g.current_invest.id, form.executor_name.data)
        db.session.add(
            Task(
                description=form.description.data,
                deadline=form.deadline.data,
                priority=form.priority.data,
                orderer=orderer,
                executor=executor,
                progress=0,
                investment_id=g.current_invest.id,
            )
        )
        db.session.commit()
        flash("You have created the task successfully.")
        notification = create_notification(
            worker_id=executor.id,
            n_type="task",
            description=f"You have a new task: '{form.description.data}' from {orderer.users.username}",
        )
        add_notification(r, notification)
        return redirect(url_for("tasks.tasks"))
    return render_template("tasks/form.html", title="Add Task", form=form)


@bp.route("/edit", methods=["GET", "POST"])
@login_required
def edit_task():
    _id = request.args.get("_id")
    next_page = request.args.get("next_page")
    if not next_page:
        next_page = url_for("tasks.tasks")
    task = Task.query.get(int(_id))
    if task:
        form = TaskForm()
        if form.validate_on_submit():
            task.description = form.description.data
            task.deadline = form.deadline.data
            task.priority = form.priority.data
            if form.executor_name != task.executor.users.username:
                task.executor = Worker.get_by_username(
                    invest_id=g.current_invest.id, username=form.executor_name.data
                )
            db.session.commit()
            flash("You have edited the task successfully.")
            return redirect(next_page)
        elif request.method == "GET":
            form.description.data = task.description
            form.deadline.data = task.deadline
            form.priority.data = task.priority
            form.executor_name.data = task.executor.users.username
        return render_template("tasks/form.html", title="Edit Task", form=form)
    return redirect(next_page)


@bp.route("/delete", methods=["GET", "POST"])
@login_required
def delete_task():
    _id = request.args.get("_id")
    next_page = request.args.get("next_page")
    if not next_page:
        next_page = url_for("tasks.tasks")
    form = WarrantyForm()
    if form.validate_on_submit():
        if form.no.data:
            flash("The task has not been deleted.")
        elif form.yes.data:
            Task.query.filter_by(id=_id).delete()
            db.session.commit()
            flash("You have deleted the task successfully.")
        return redirect(next_page)
    return render_template("warranty_form.html", title="Delete Task", form=form)


@bp.route("/change", methods=["GET", "POST"])
@login_required
def change_progress():
    _id = request.args.get("_id")
    next_page = request.args.get("next_page")
    if not next_page:
        next_page = url_for("tasks.tasks")
    task = Task.query.get(int(_id))
    if task:
        form = ProgressForm()
        if form.validate_on_submit():
            task.progress = form.progress.data
            db.session.commit()
            flash("You have changed the progress successfully.")
            return redirect(next_page)
        elif request.method == "GET":
            form.progress.data = task.progress
        return render_template("tasks/form.html", title="Change Progress", form=form)
    return redirect(next_page)

app/templates/tasks/form.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title_content %}Tasks{% endblock %}
{% block app_content %}
    <h5>Create new task:</h5>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/tasks/tasks.html
{% extends "base.html" %}

{% block title_content %}{{ title }}{% endblock %}

{% block button_content %}
    <div class="btn-toolbar mb-2 mb-md-0">
      {% if g.current_invest.name %}
        <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <a href="{{ url_for('tasks.add_task') }}">Add Task</a>
            </button>
            {% if title != 'Tasks' %}
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <a href="{{ url_for('tasks.tasks') }}">Tasks</a>
            </button>
            {% endif %}
            {% if title != 'My Tasks' %}
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <a href="{{ url_for('tasks.my_tasks') }}">My Tasks</a>
            </button>
            {% endif %}
            {% if title != 'Deputed Tasks' %}
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <a href="{{ url_for('tasks.deputed_tasks') }}">Deputed Tasks</a>
            </button>
            {% endif %}
        </div>
      {% else %}
        <div class="container">
          <h6>No Investment selected.</h6><br>
        </div>
        <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <a href="{{ url_for('investments.invest_list') }}">Select Investment</a>
            </button>
        </div>
      {% endif %}
    </div>

{% endblock %}
{% block app_content %}

<main>
  <div class="table-responsive">
    {% if g.current_invest.name %}

        {% if new_tasks %}
        <h5>New Tasks</h5><br>
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="text-center">Description</th>
              <th class="text-center">Deadline</th>
                <th class="text-center">Priority</th>
                <th class="text-center">Orderer</th>
                <th class="text-center">Executor</th>
                <th class="text-center">Progress</th>
                <th class="text-center">Creation Date</th>
                <th class="text-center"></th>
            </tr>
          </thead>
          <tbody>
        {% for task in new_tasks %}
          <tr>
              <td class="text-center">{{ task.description }}</td>
              <td class="text-center">{{ task.deadline.strftime('%Y-%m-%d') }}</td>
              <td class="text-center">{{ task.priority }}</td>
              <td class="text-center">
                  <a href="{{ url_for('main.user', username=task.orderer.users.username) }}" >
                      {{ task.orderer.users.username }}
                  </a>
              </td>
              <td class="text-center">
                  <a href="{{ url_for('main.user', username=task.executor.users.username) }}" >
                      {{ task.executor.users.username }}
                  </a>
              </td>
              <td class="text-center">{{ task.progress }}</td>
              <td class="text-center">{{ task.created_at.strftime('%Y-%m-%d %H:%M') }}</td>
              <td class="text-center">
                  <div class="btn-toolbar mb-2 mb-md-0">
                      <div class="btn-group mr-1">
                          {% if task.orderer.user_id == current_user.id %}
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                              <a href="{{ url_for('tasks.edit_task', _id=task.id, next_page=next_page) }}">Edit</a>
                          </button>
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                              <a href="{{ url_for('tasks.delete_task', _id=task.id, next_page=next_page) }}">Delete</a>
                          </button>
                          {% endif %}
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                              <a href="{{ url_for('tasks.change_progress', _id=task.id, next_page=next_page) }}">Change Progress</a>
                          </button>
                      </div>
                  </div>
              </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      {% endif %}

        {% if tasks_in_progress %}
        <h5>Tasks in progress</h5><br>
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="text-center">Description</th>
              <th class="text-center">Deadline</th>
                <th class="text-center">Priority</th>
                <th class="text-center">Orderer</th>
                <th class="text-center">Executor</th>
                <th class="text-center">Progress</th>
                <th class="text-center">Creation Date</th>
                <th class="text-center"></th>
            </tr>
          </thead>
          <tbody>
        {% for task in tasks_in_progress %}
          <tr>
              <td class="text-center">{{ task.description }}</td>
              <td class="text-center">{{ task.deadline.strftime('%Y-%m-%d') }}</td>
              <td class="text-center">{{ task.priority }}</td>
              <td class="text-center">
                  <a href="{{ url_for('main.user', username=task.orderer.users.username) }}" >
                      {{ task.orderer.users.username }}
                  </a>
              </td>
              <td class="text-center">
                  <a href="{{ url_for('main.user', username=task.executor.users.username) }}" >
                      {{ task.executor.users.username }}
                  </a>
              </td>
              <td class="text-center">{{ task.progress }}</td>
              <td class="text-center">{{ task.created_at.strftime('%Y-%m-%d %H:%M') }}</td>
              <td class="text-center">
                  <div class="btn-toolbar mb-2 mb-md-0">
                      <div class="btn-group mr-1">
                          {% if task.orderer.user_id == current_user.id %}
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                              <a href="{{ url_for('tasks.edit_task', _id=task.id, next_page=next_page) }}">Edit</a>
                          </button>
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                              <a href="{{ url_for('tasks.delete_task', _id=task.id, next_page=next_page) }}">Delete</a>
                          </button>
                          {% endif %}
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                              <a href="{{ url_for('tasks.change_progress', _id=task.id, next_page=next_page) }}">Change Progress</a>
                          </button>
                      </div>
                  </div>
              </td>
          </tr>
        {% endfor %}
          </tbody>
        </table>
      {% else %}
        <p>No tasks added yet.</p>
      {% endif %}

      {% if realized_tasks %}
        <h5>Realized tasks</h5><br>
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="text-center">Description</th>
              <th class="text-center">Deadline</th>
                <th class="text-center">Priority</th>
                <th class="text-center">Orderer</th>
                <th class="text-center">Executor</th>
                <th class="text-center">Progress</th>
                <th class="text-center">Creation Date</th>
                <th class="text-center"></th>
            </tr>
          </thead>
          <tbody>
        {% for task in realized_tasks %}
          <tr>
              <td class="text-center">{{ task.description }}</td>
              <td class="text-center">{{ task.deadline.strftime('%Y-%m-%d') }}</td>
              <td class="text-center">{{ task.priority }}</td>
              <td class="text-center">
                  <a href="{{ url_for('main.user', username=task.orderer.users.username) }}" >
                      {{ task.orderer.users.username }}
                  </a>
              </td>
              <td class="text-center">
                  <a href="{{ url_for('main.user', username=task.executor.users.username) }}" >
                      {{ task.executor.users.username }}
                  </a>
              </td>
              <td class="text-center">{{ task.progress }}</td>
              <td class="text-center">{{ task.created_at.strftime('%Y-%m-%d %H:%M') }}</td>
              <td class="text-center">
                  <div class="btn-toolbar mb-2 mb-md-0">
                      <div class="btn-group mr-1">
                          {% if task.orderer.user_id == current_user.id %}
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                              <a href="{{ url_for('tasks.edit_task', _id=task.id, next_page=next_page) }}">Edit</a>
                          </button>
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                              <a href="{{ url_for('tasks.delete_task', _id=task.id, next_page=next_page) }}">Delete</a>
                          </button>
                          {% endif %}
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                              <a href="{{ url_for('tasks.change_progress', _id=task.id, next_page=next_page) }}">Change Progress</a>
                          </button>
                      </div>
                  </div>
              </td>
          </tr>
        {% endfor %}
          </tbody>
        </table>
      {% endif %}
  {% endif %}
  </div>
</main>
{% endblock %}