app/documents/forms.py
import os

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError


class NewFolderForm(FlaskForm):
    folder_name = StringField("Folder Name", validators=[DataRequired()])
    submit = SubmitField("Submit")

    def __init__(self, folder_path: str, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.folder_path = folder_path

    def validate_folder_name(self, folder_name):
        if os.path.exists(os.path.join(self.folder_path, folder_name.data)):
            raise ValidationError("Folder with this name already exists!")

app/documents/__init__.py
from flask import Blueprint

bp = Blueprint("documents", __name__)

from app.documents import routes

app/documents/routes.py
import glob
import os

from flask import (
    render_template,
    redirect,
    url_for,
    request,
    flash,
    send_from_directory,
    g,
)
from flask_login import login_required
from werkzeug.utils import secure_filename

from app.app_tasks import tasks
from app.documents import bp
from app.documents.forms import NewFolderForm
from app.handling_files import allowed_file, save_file
from app.handling_files import (
    remove,
    create_new_folder,
    get_metadata,
    get_current_and_prev_path,
)
from app.main.forms import WarrantyForm


@bp.route("/")
@login_required
def documents() -> str:
    if not g.current_invest.id:
        flash("Choose investment first.")
        return redirect(url_for("investments.invest_list"))
    current_path, prev_path = get_current_and_prev_path()
    paths = glob.glob(current_path + "/*")
    files, folders = get_metadata(paths)
    return render_template(
        "/documents/documents.html",
        title="Documents",
        files=files,
        folders=folders,
        current_path=current_path,
        prev_path=prev_path,
    )


@bp.route("/new_folder", methods=["GET", "POST"])
@login_required
def new_folder() -> str:
    current_path, prev_path = get_current_and_prev_path()
    form = NewFolderForm(current_path)
    if form.validate_on_submit():
        create_new_folder(current_path, secure_filename(form.folder_name.data))
        flash("You created new folder successfully.")
        return redirect(
            url_for(
                "documents.documents", current_path=current_path, prev_path=prev_path
            )
        )
    return render_template(
        "documents/form.html",
        title="Create New Folder",
        form=form,
        current_path=current_path,
    )


@bp.route("/upload_files", methods=["GET", "POST"])
@login_required
def upload_files():
    if request.method == "POST":
        current_path, prev_path = get_current_and_prev_path()
        if "file[]" not in request.files:
            flash("No file part.")
            return redirect(request.url)
        files = request.files.getlist("file[]")
        for file in files:
            if file.filename == "":
                flash("No selected file.")
                return redirect(request.url)
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                try:
                    save_file(
                        file,
                        current_path,
                        filename,
                    )
                except FileExistsError:
                    flash("File with this name already exists.")
                else:
                    flash("New file uploaded successfully.")
        return redirect(
            url_for(
                "documents.documents", current_path=current_path, prev_path=prev_path
            )
        )
    return render_template("upload_file_form.html")


@bp.route("/delete", methods=["GET", "POST"])
@login_required
def delete() -> str:
    form = WarrantyForm()
    if form.validate_on_submit():
        current_path, prev_path = get_current_and_prev_path()
        if form.yes.data:
            filename = request.args.get("filename")
            file_path = os.path.join(current_path, filename)
            remove(file_path)
        return redirect(
            url_for(
                "documents.documents", current_path=current_path, prev_path=prev_path
            )
        )
    return render_template("warranty_form.html", title="Delete Item", form=form)


@bp.route("/download_file", methods=["GET", "POST"])
@login_required
def download_file():
    current_path, prev_path = get_current_and_prev_path()
    filename = request.args.get("filename")
    if filename:
        return send_from_directory(current_path, filename, as_attachment=True)


@bp.route("/make_archive", methods=["GET", "POST"])
@login_required
def make_archive():
    current_path, prev_path = get_current_and_prev_path()
    catalog_to_archive = request.args.get("catalog_to_archive")
    if catalog_to_archive:
        tasks.archive_and_save.delay(
            current_path, catalog_to_archive, g.current_worker.id
        )
        flash(
            "The archiving is started. Wait for notification that you can download the file."
        )
    return redirect(
        url_for("documents.documents", current_path=current_path, prev_path=prev_path)
    )

app/templates/documents/documents.html
{% extends "base.html" %}

{% block title_content %}{{ title }}{% endblock %}
{% block button_content %}

<div class="btn-toolbar mb-2 mb-md-0">
  {% if g.current_invest.name %}
      <div class="btn-group mr-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <a href="{{ url_for('documents.documents', current_path=prev_path) }}">Back</a>
        </button>
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <a href="{{ url_for('documents.new_folder', current_path=current_path) }}">Add new folder</a>
        </button>
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <a href="{{ url_for('documents.upload_files', current_path=current_path) }}">Add new files</a>
        </button>
      </div>
      {% else %}
        <div class="container">
          <h6>No Investment selected.</h6><br>
        </div>
        <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <a href="{{ url_for('investments.invest_list') }}">Select Investment</a>
            </button>
        </div>
      {% endif %}
</div>

{% endblock %}
{% block app_content %}

<main>
      <div class="table-responsive">
    {% if g.current_invest.name %}
        <table class="table table-striped table-sm small">
          <thead>
            <tr>
              <th class="text-center">Name</th>
              <th class="text-center">Last modified</th>
              <th class="text-center">Created</th>
              <th class="text-center"></th>
            </tr>
          </thead>
          <tbody>
		  {% for folder in folders %}
		  <tr>
		      <td class="text-center"><a href="{{ url_for('documents.documents', current_path=current_path, catalog=folder.name) }}">{{ folder.name }}</a></td>
              <td class="text-center">{{ folder.last_modified }}</td>
		      <td class="text-center">{{ folder.created_at }}</td>
		      <td class="text-center">
                  <div class="btn-toolbar mb-2 mb-md-0">
                      <div class="btn-group mr-1">
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                            <a href="{{ url_for('documents.make_archive', current_path=current_path, catalog_to_archive=folder.name) }}">Archive</a>
                          </button>
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                            <a href="{{ url_for('documents.delete', current_path=current_path, filename=folder.name) }}">Delete</a>
                          </button>
                      </div>
                  </div>
			  </td>
          </tr>
		  {% endfor %}
          		  {% for file in files %}
		  <tr>
		      <td class="text-center">{{ file.name }}</td>
              <td class="text-center">{{ file.last_modified }}</td>
		      <td class="text-center">{{ file.created_at }}</td>
		      <td class="text-center">
                  <div class="btn-toolbar mb-2 mb-md-0">
                      <div class="btn-group mr-1">
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                            <a href="{{ url_for('documents.download_file', current_path=current_path, filename=file.name) }}">Download</a>
                          </button>
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                            <a href="{{ url_for('documents.delete', current_path=current_path, filename=file.name) }}">Delete</a>
                          </button>
                      </div>
                  </div>
			  </td>
          </tr>
		  {% endfor %}
          </tbody>
        </table>
    {% endif %}
      </div>
</main>

{% endblock %}

app/templates/documents/form.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block button_content %}

<div class="btn-toolbar mb-2 mb-md-0">
  {% if g.current_invest.name %}
      <div class="btn-group mr-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <a href="{{ url_for('documents.documents', current_path=current_path) }}">Back</a>
        </button>
      </div>
      {% endif %}
</div>
{% endblock %}

{% block title_content %}{{ title }}{% endblock %}
{% block app_content %}
    <br>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}