app/production/custom_registry/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField
from wtforms.validators import DataRequired, ValidationError

from app.production.custom_registry.registry import Registry, Function


class CreateTableForm(FlaskForm):
    table_name = StringField("Table Name", validators=[DataRequired()])
    submit = SubmitField("Create")

    def __init__(self, invest_id: int, username: str, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.invest_id = invest_id
        self.username = username
        self.registry = None

    def validate_table_name(self, table_name):
        try:
            self.registry = Registry(self.invest_id, self.username, table_name.data)
        except ValueError as e:
            raise ValidationError(e.__str__())


class AddColumnForm(FlaskForm):
    name = StringField("Column Name", validators=[DataRequired()])
    data_type = SelectField("Data Type", choices=["string", "integer", "float", "bool"])
    submit = SubmitField("Create")

    def __init__(
        self, invest_id: int, username: str, registry_name: str, *args, **kwargs
    ):
        super().__init__(*args, **kwargs)
        self.registry = Registry(invest_id, username, registry_name)

    def validate_name(self, name):
        if name.data in self.registry.get_fields():
            raise ValidationError("Field with this name already exits.")


class AddFunctionForm(FlaskForm):
    first_field = SelectField("First Field")
    second_field = SelectField("Second Field")
    operator = SelectField("Choose Operator")
    func_field_name = StringField("New Field Name", validators=[DataRequired()])
    submit = SubmitField("Create")

    def __init__(
        self, invest_id: int, username: str, registry_name: str, *args, **kwargs
    ):
        super().__init__(*args, **kwargs)
        self.registry = Registry(invest_id, username, registry_name)
        self.first_field.choices = self.registry.get_fields(numeric_fields=True)
        self.second_field.choices = self.registry.get_fields(numeric_fields=True)
        self.operator.choices = Function.operators()

app/production/custom_registry/__init__.py
from flask import Blueprint

bp = Blueprint("custom_registry", __name__)

from app.production.custom_registry import routes

app/production/custom_registry/routes.py
from flask import render_template, redirect, url_for, request, g, flash
from flask_login import login_required, current_user
from flask_wtf import FlaskForm

from app.production.custom_registry import bp
from app.production.custom_registry.forms import (
    CreateTableForm,
    AddColumnForm,
    AddFunctionForm,
)
from app.production.custom_registry.registry import RegistryStore, Registry


@bp.route("/")
@login_required
def start():
    registries = RegistryStore.get_user_registries(
        g.current_invest.id, current_user.username
    )
    return render_template(
        "production/custom_registry/start.html",
        title="Custom Registry",
        registries=registries,
    )


@bp.route("/create_table", methods=["GET", "POST"])
@login_required
def create_table():
    form = CreateTableForm(g.current_invest.id, current_user.username)
    if form.validate_on_submit():
        registry_name = form.table_name.data
        return redirect(
            url_for("custom_registry.add_column", registry_name=registry_name)
        )
    return render_template(
        "production/custom_registry/form.html", title="Create Table", form=form
    )


@bp.route("/add_column", methods=["GET", "POST"])
@login_required
def add_column():
    registry_name = request.args.get("registry_name")
    form = AddColumnForm(g.current_invest.id, current_user.username, registry_name)
    if form.validate_on_submit():
        name = form.name.data
        data_type = form.data_type.data
        form.registry.add_field(name, data_type)
        return redirect(
            url_for("custom_registry.registry", registry_name=registry_name)
        )
    return render_template(
        "production/custom_registry/form.html", title="Add Column", form=form
    )


@bp.route("/registry", methods=["GET", "POST"])
@login_required
def registry():
    registry_name = request.args.get("registry_name")
    reg = Registry(g.current_invest.id, current_user.username, registry_name)
    return render_template(
        "production/custom_registry/registry.html",
        title=registry_name,
        registry=reg,
    )


@bp.route("/add_data", methods=["GET", "POST"])
@login_required
def add_data():
    registry_name = request.args.get("registry_name")
    reg = Registry(g.current_invest.id, current_user.username, registry_name)
    ItemForm = type("ItemForm", (FlaskForm,), reg.get_form_fields())
    form = ItemForm()
    if form.validate_on_submit():
        reg.add_item(form.data)
        return redirect(
            url_for("custom_registry.registry", registry_name=registry_name)
        )
    return render_template(
        "production/custom_registry/form.html", title="Add Data", form=form
    )


@bp.route("/edit_item", methods=["GET", "POST"])
@login_required
def edit_item():
    _id = request.args.get("_id")
    registry_name = request.args.get("registry_name")
    reg = Registry(g.current_invest.id, current_user.username, registry_name)
    ItemForm = type("ItemForm", (FlaskForm,), reg.get_form_fields())
    form = ItemForm()
    if form.validate_on_submit():
        reg.edit_item(_id, form.data)
        return redirect(
            url_for("custom_registry.registry", registry_name=registry_name)
        )
    return render_template(
        "production/custom_registry/form.html", title="Add Data", form=form
    )


@bp.route("/delete_item", methods=["GET", "POST"])
@login_required
def delete_item():
    _id = request.args.get("_id")
    registry_name = request.args.get("registry_name")
    reg = Registry(g.current_invest.id, current_user.username, registry_name)
    reg.delete_item(_id)
    return redirect(url_for("custom_registry.registry", registry_name=registry_name))


@bp.route("/delete_registry", methods=["GET", "POST"])
@login_required
def delete_registry():
    registry_name = request.args.get("registry_name")
    reg = Registry(g.current_invest.id, current_user.username, registry_name)
    reg.delete_registry()
    return redirect(url_for("custom_registry.start"))


@bp.route("/add_function", methods=["GET", "POST"])
@login_required
def add_function():
    registry_name = request.args.get("registry_name")
    form = AddFunctionForm(g.current_invest.id, current_user.username, registry_name)
    if form.validate_on_submit():
        form.registry.add_function_field(
            form.first_field.data,
            form.second_field.data,
            form.operator.data,
            form.func_field_name.data,
        )
        return redirect(
            url_for("custom_registry.registry", registry_name=registry_name)
        )
    return render_template(
        "production/custom_registry/form.html", title="Add Function", form=form
    )

app/production/masonry_works/__init__.py
from flask import Blueprint

bp = Blueprint("masonry_works", __name__)

from app.production.masonry_works import routes

app/production/masonry_works/routes.py
from flask import render_template, flash, redirect, url_for, request, g
from flask_login import login_required
from werkzeug.utils import secure_filename

from app.handling_files import allowed_file, save_file, handle_csv
from app.main.forms import WarrantyForm
from app.models import Hole, Processing, Wall
from app.production.masonry_works import bp
from app.production.masonry_works.data_treatment import TotalAreas, Categories
from app.production.masonry_works.forms import (
    WallForm,
    HoleForm,
    ProcessingForm,
)


@bp.route("/walls")
@login_required
def walls() -> str:
    sector = request.args.get("sector")
    level = request.args.get("level")
    localization = request.args.get("localization")
    brick_type = request.args.get("brick_type")
    wall_width = request.args.get("wall_width")
    items = Wall.get_all_items(g.current_invest.id)
    if sector:
        items = items.filter_by(sector=sector)
    if level:
        items = items.filter_by(level=level)
    if localization:
        items = items.filter_by(localization=localization)
    if brick_type:
        items = items.filter_by(brick_type=brick_type)
    if wall_width:
        items = items.filter_by(wall_width=wall_width)
    items = items.order_by("local_id").all()
    total = TotalAreas(items)
    return render_template(
        "production/masonry_works/walls.html",
        title="Walls",
        items=items,
        total=total,
        categories=Categories(Wall),
    )


@bp.route("/holes")
@login_required
def holes() -> str:
    wall_id = request.args.get("wall_id")
    items = Hole.get_items_by_wall_id(wall_id)
    return render_template(
        "production/masonry_works/holes.html",
        title="Holes",
        items=items,
        wall_id=wall_id,
    )


@bp.route("/processing")
@login_required
def processing() -> str:
    wall_id = request.args.get("wall_id")
    items = Processing.get_items_by_wall_id(wall_id)
    left_to_sale = Wall.get_left_to_sale(wall_id)
    return render_template(
        "production/masonry_works/processing.html",
        title="Processing",
        items=items,
        wall_id=wall_id,
        left_to_sale=left_to_sale,
    )


@bp.route("/modify")
@login_required
def modify() -> str:
    wall_id = request.args.get("wall_id")
    item = Wall.query.filter_by(id=wall_id).first()
    return render_template(
        "production/masonry_works/modify.html", title="Modify", item=item
    )


@bp.route("/add_wall", methods=["GET", "POST"])
@login_required
def add_wall() -> str:
    form = WallForm(g.current_invest.id)
    if form.validate_on_submit():
        Wall.add_wall(g.current_invest.id, **form.data)
        flash("You added a new wall.")
        return redirect(url_for("masonry_works.walls"))
    return render_template(
        "production/masonry_works/forms/wall_form.html", title="Add Wall", form=form
    )


@bp.route("/add_hole", methods=["GET", "POST"])
@login_required
def add_hole() -> str:
    wall_id = request.args.get("wall_id")
    form = HoleForm()
    if form.validate_on_submit():
        Wall.add_hole(wall_id, **form.data)
        flash("You added a new hole.")
        next_page = request.args.get("next_page")
        if not next_page:
            next_page = url_for("masonry_works.modify", wall_id=wall_id)
        return redirect(next_page)
    return render_template(
        "production/masonry_works/forms/hole_form.html", title="Add Hole", form=form
    )


@bp.route("/add_processing", methods=["GET", "POST"])
@login_required
def add_processing() -> str:
    wall_id = request.args.get("wall_id")
    form = ProcessingForm()
    if form.validate_on_submit():
        Wall.add_processing(wall_id, **form.data)
        flash("You added a new processing.")
        next_page = request.args.get("next_page")
        if not next_page:
            next_page = url_for("masonry_works.modify", wall_id=wall_id)
        return redirect(next_page)
    return render_template(
        "production/masonry_works/forms/processing_form.html",
        title="Add Processing",
        form=form,
    )


@bp.route("/edit_wall", methods=["GET", "POST"])
@login_required
def edit_wall() -> str:
    wall_id = request.args.get("wall_id")
    wall = Wall.query.filter_by(id=wall_id).first()
    form = WallForm(invest_id=g.current_invest.id, original_local_id=wall.local_id)
    if form.validate_on_submit():
        Wall.edit_wall(wall_id, **form.data)
        flash("You modified the wall.")
        return redirect(url_for("masonry_works.modify", wall_id=wall_id))
    elif request.method == "GET":
        form.local_id.data = wall.local_id
        form.sector.data = wall.sector
        form.level.data = wall.level
        form.localization.data = wall.localization
        form.brick_type.data = wall.brick_type
        form.wall_width.data = wall.wall_width
        form.wall_length.data = wall.wall_length
        form.floor_ord.data = wall.floor_ord
        form.ceiling_ord.data = wall.ceiling_ord
    return render_template(
        "production/masonry_works/forms/wall_form.html",
        title="Edit Wall",
        form=form,
    )


@bp.route("/edit_hole", methods=["GET", "POST"])
@login_required
def edit_hole() -> str:
    wall_id = request.args.get("wall_id")
    hole_id = request.args.get("hole_id")
    hole = Hole.query.filter_by(id=hole_id).first()
    form = HoleForm()
    if form.validate_on_submit():
        Wall.edit_hole(hole_id, **form.data)
        flash("You modified the hole.")
        return redirect(url_for("masonry_works.holes", wall_id=wall_id))
    elif request.method == "GET":
        form.width.data = hole.width
        form.height.data = hole.height
        form.amount.data = hole.amount
    return render_template(
        "production/masonry_works/forms/hole_form.html",
        title="Edit Hole",
        form=form,
    )


@bp.route("/edit_processing", methods=["GET", "POST"])
@login_required
def edit_processing() -> str:
    wall_id = request.args.get("wall_id")
    proc_id = request.args.get("proc_id")
    processing = Processing.query.filter_by(id=proc_id).first()
    form = ProcessingForm()
    if form.validate_on_submit():
        Wall.edit_processing(proc_id, **form.data)
        flash("You modified the processing.")
        return redirect(url_for("masonry_works.processing", wall_id=wall_id))
    elif request.method == "GET":
        form.year.data = processing.year
        form.month.data = processing.month
        form.done.data = processing.done
    return render_template(
        "production/masonry_works/forms/processing_form.html",
        title="Edit Processing",
        form=form,
    )


@bp.route("/delete_wall", methods=["GET", "POST"])
@login_required
def delete_wall() -> str:
    wall_id = request.args.get("wall_id")
    form = WarrantyForm()
    if form.validate_on_submit():
        if form.no.data:
            flash("Wall has not been deleted.")
            next_page = request.args.get("next_page")
            if not next_page:
                next_page = url_for("masonry_works.walls")
            return redirect(next_page)
        elif form.yes.data:
            Wall.delete_wall(wall_id)
            flash("Wall has been deleted.")
            return redirect(url_for("masonry_works.walls"))
    return render_template(
        "warranty_form.html",
        title="Delete Wall",
        form=form,
    )


@bp.route("/delete_hole", methods=["GET", "POST"])
@login_required
def delete_hole() -> str:
    wall_id = request.args.get("wall_id")
    hole_id = request.args.get("hole_id")
    form = WarrantyForm()
    if form.validate_on_submit():
        if form.no.data:
            flash("Hole has not been deleted.")
        elif form.yes.data:
            Wall.delete_hole(hole_id)
            flash("Hole has been deleted.")
        return redirect(url_for("masonry_works.holes", wall_id=wall_id))
    return render_template(
        "warranty_form.html",
        title="Delete Hole",
        form=form,
    )


@bp.route("/delete_processing", methods=["GET", "POST"])
@login_required
def delete_processing() -> str:
    wall_id = request.args.get("wall_id")
    proc_id = request.args.get("proc_id")
    form = WarrantyForm()
    if form.validate_on_submit():
        if form.no.data:
            flash("Processing has not been deleted.")
        elif form.yes.data:
            Wall.delete_processing(proc_id)
            flash("Processing has been deleted.")
        return redirect(url_for("masonry_works.processing", wall_id=wall_id))
    return render_template(
        "warranty_form.html",
        title="Delete Processing",
        form=form,
    )


@bp.route("/upload_files", methods=["GET", "POST"])
@login_required
def upload_files() -> str:
    if request.method == "POST":
        if not g.current_invest.id:
            flash("Choose investment first.")
            return redirect(url_for("investments.invest_list"))
        model = request.args.get("model")
        if not model:
            return redirect(url_for("masonry_works.wall"))
        if "file[]" not in request.files:
            flash("No file part.")
            return redirect(request.url)
        files = request.files.getlist("file[]")
        for file in files:
            if file.filename == "":
                flash("No selected file.")
                return redirect(request.url)
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                try:
                    save_file(
                        file=file,
                        file_dir="",
                        filename=filename,
                        temp=True,
                    )
                except FileExistsError:
                    flash("File with this name already exists.")
                else:
                    messages = handle_csv(filename, g.current_invest.id, model, Wall)
                    for message in messages:
                        flash(message)

app/templates/production/custom_registry/form.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title_content %}{{ title }}{% endblock %}
{% block app_content %}
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/production/custom_registry/registry.html
{% extends "base.html" %}

{% block title_content %}{{ title }}{% endblock %}
{% block button_content %}

<div class="btn-toolbar mb-2 mb-md-0">
  <div class="btn-group mr-2">
    <button type="button" class="btn btn-sm btn-outline-secondary">
      <a href="{{ url_for('custom_registry.start') }}">Back</a>
    </button>
    <button type="button" class="btn btn-sm btn-outline-secondary">
      <a href="{{ url_for('custom_registry.add_data', registry_name=title) }}">Add Data</a>
    </button>
    <button type="button" class="btn btn-sm btn-outline-secondary">
      <a href="{{ url_for('custom_registry.add_column', registry_name=title) }}">Add New Column</a>
    </button>
    <button type="button" class="btn btn-sm btn-outline-secondary">
      <a href="{{ url_for('custom_registry.add_function', registry_name=title) }}">Add New Function</a>
    </button>
  </div>
</div>

{% endblock %}
{% block app_content %}

<main>
      <div class="table-responsive">
        <table class="table table-striped table-sm small">

          <thead>
            <tr>
              {% for field_name in registry.get_fields() %}
              <th class="text-center">
                <div class="btn-group">
                    {{ field_name }}
                </div>
              </th>
              {% endfor %}
            </tr>
          </thead>

          <tbody>
		  {% for item in registry.get_items() %}
		  <tr>
              {% for field_name in registry.get_fields() %}
                {% if field_name in item.keys() %}
    		      <td class="text-center">{{ item.__getitem__(field_name) }}</td>
                {% else %}
    		      <td class="text-center"></td>
                {% endif %}
              {% endfor %}
		      <td class="text-center">
                  <div class="btn-toolbar mb-2 mb-md-0">
                      <div class="btn-group mr-1">
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                              <a href="{{ url_for('custom_registry.edit_item', _id=item._id, registry_name=title) }}">Edit</a>
                          </button>
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                            <a href="{{ url_for('custom_registry.delete_item', _id=item._id, registry_name=title) }}">Delete</a>
                          </button>
                      </div>
                  </div>
			  </td>
          </tr>
		  {% endfor %}
          </tbody>

        </table>
      </div>
    </main>
{% endblock %}

app/templates/production/custom_registry/start.html
{% extends "base.html" %}

{% block title_content %}{{ title }}{% endblock %}
{% block button_content %}

<div class="btn-toolbar mb-2 mb-md-0">
  <div class="btn-group mr-2">
    <button type="button" class="btn btn-sm btn-outline-secondary">
      <a href="{{ url_for('custom_registry.create_table') }}">Create New Registry</a>
    </button>
  </div>
</div>

{% endblock %}
{% block app_content %}

<main>
      <div class="table-responsive">
        <table class="table table-striped">

          <thead>
            <tr>
              {% for field_name in field_names %}
              <th class="text-center">
                <div class="btn-group">
                    {{ field_name }}
                </div>
              </th>
              {% endfor %}
            </tr>
          </thead>

          <tbody>

          {% for registry in registries %}
		  <tr>
              <td class="text-center">
                <a href="{{ url_for('custom_registry.registry', registry_name=registry) }}">{{ registry }}</a><br>
              </td>
		      <td class="text-center">
                  <div class="btn-toolbar mb-2 mb-md-0">
                      <div class="btn-group mr-1">
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                              <a href="{{ url_for('custom_registry.add_column', registry_name=registry) }}">Add New Column</a>
                          </button>
                          <button type="button" class="btn btn-sm btn-outline-secondary">
                              <a href="{{ url_for('custom_registry.delete_registry', registry_name=registry) }}">Delete Registry</a>
                          </button>
                      </div>
                  </div>
			  </td>
          </tr>
		  {% endfor %}

          </tbody>

        </table>
      </div>
    </main>

{% endblock %}